services:
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: so-backend
    ports:
      - "8000:8000"
    environment:
      - ELASTICSEARCH_HOST=http://so-elastic:9200
    depends_on:
      - elasticsearch
    networks:
      - so-network

  postgres:
    image: postgres:16
    container_name: so-postgres
    environment:
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_password
      POSTGRES_DB: stackoverflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - so-network


  ingest:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: so-ingest
    environment:
      - ELASTICSEARCH_HOST=http://so-elastic:9200
      - PYTHONPATH=/app
    command: python scripts/ingest_data.py
    depends_on:
      - elasticsearch
    networks:
      - so-network


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@so.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - so-network

  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: so-elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # turning off passwords for local dev
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - so-network
    volumes:
      - es_data:/usr/share/elasticsearch/data



networks:
  so-network:
    driver: bridge

volumes:
  postgres_data:
  es_data: